from pathlib import Path

path = Path('writing/benevolent_outsider_draft_04_method_primitive_1921_1933.md')
text = path.read_text(encoding='utf-8')

old = "The order inside those two December letters matters. Malinowski did not send a single abstract programme. Huizinga received a small, a medium and a large book and made a reading choice among them, beginning with *Crime and Custom*. The Milo joke gives that choice a physical sequence: calf first, heavier animal later. Huizinga then returned from the book to their earlier walk and from the walk to his own historical craft. By 31 December the traffic had moved again. The formulation about ‘the functional side’ was followed not by a declaration of allegiance but by a string of historical objects—medieval law, feudal relations, troubadour culture, the force of words, and sentiments such as vanity, generosity and friendship. What had arrived as books was already being redistributed across a historian’s problems."
new = "The order inside those two December letters matters. Malinowski did not send a single abstract programme. Huizinga received a small, a medium and a large book and made a reading choice among them, beginning with *Crime and Custom*. The Milo joke gives that choice a physical sequence: calf first, heavier animal later. Huizinga then returned from the book to their earlier walk and from the walk to his own historical craft. By 31 December the traffic had moved again. The formulation about ‘the functional side’ was followed not by a declaration of allegiance but by a string of historical objects—medieval law, feudal relations, troubadour culture, the force of words, and sentiments such as vanity, generosity and friendship. The force of words was not a new object: in the 1919 first edition of *Herfsttij*, Huizinga had already described belief in `de werking van het gesproken woord` as fully manifest in primitive culture and persisting in late-medieval blessings, magical formulas and legal formulas.[^24] What had arrived as books was already being redistributed across a historian’s problems."
if old not in text:
    raise SystemExit('body anchor not found')
text = text.replace(old, new, 1)

old_note = "[^24]: Johan Huizinga, *Herfsttij der Middeleeuwen* (Haarlem: H.D. Tjeenk Willink & Zoon, 1919), chapter on symbolism. The wording `van ethnologisch gezichtspunt ... een zeer primitieve geestesfunctie` and the following account of `het primitieve denken` are present in the 1919 first-edition scan (verified against Dutch Wikisource, scan p. 182) as well as the later collected-works text, DBNL TEI `sources/dbnl/verzamelde_werken/huiz003verz04_01.xml`, p. 247. This occurrence is used only as a pre-contact history of the category, not as an analogy between late-medieval civilization and the later history of *primitive*."
new_note = "[^24]: Johan Huizinga, *Herfsttij der Middeleeuwen* (Haarlem: H.D. Tjeenk Willink & Zoon, 1919). In the symbolism chapter, the wording `van ethnologisch gezichtspunt ... een zeer primitieve geestesfunctie` and the following account of `het primitieve denken` are present in the 1919 first-edition scan (verified against Dutch Wikisource, scan p. 182) as well as the later collected-works text, DBNL TEI `sources/dbnl/verzamelde_werken/huiz003verz04_01.xml`, p. 247. In chapter XVII Huizinga likewise writes that belief in `de werking van het gesproken woord` `zich in de primitieve cultuur in zijn volheid openbaart` and persists in late-medieval blessings, magical formulas and `dingtalen`; this wording is also present in the 1919 first-edition scan (verified against Dutch Wikisource, scan p. 214) and in the collected-works text, pp. 292–293. These occurrences are used as pre-contact controls on Huizinga's category and historical problems, not as an analogy between late-medieval civilization and the later history of *primitive*."
if old_note not in text:
    raise SystemExit('note anchor not found')
text = text.replace(old_note, new_note, 1)

path.write_text(text, encoding='utf-8')
