from pathlib import Path

path = Path('writing/benevolent_outsider_draft_04_method_primitive_1921_1933.md')
text = path.read_text(encoding='utf-8')
old = "The encounter met an existing repertoire. Huizinga later remembered reaching history from Sanskrit and comparative linguistics by a ‘salto mortale’; he also admitted that his early teaching preferred a vivid story to critical groundedness (Huizinga, 1947). In 1921, reviewing Wells’s attempt to extend world history from planetary and biological development into human history, Huizinga objected that geological or biological *ontwikkeling* had little to do with ‘de functie van het historisch begrijpen’; a wider chronology did not by itself yield historical understanding (Huizinga, 1921). His critique of Spengler made the same problem comparative: exact homologies across civilizations forced particulars onto the Procrustean bed of a system, while *Preussentum und Sozialismus* turned the operation political through a *historisch-ethnografische tegenstelling* between English and Prussian character (Huizinga, 1921). On 7 April 1926, only days before his transatlantic crossing—and six days before a surviving letter places him aboard the *Berengaria*[^25]—he attacked *evolutie* as a general historical principle, defined cultural history as social morphology concerned with what connects people to one another rather than with what holds them together internally, and placed ethnology among the special cultural sciences already practising such morphology (Huizinga, 1927: 5–7). In the same theses he warned that general culture-historical terms could acquire a mythological element and suffer inflation, while period names that purported to state an era’s essence could prejudge and mislead (Huizinga, 1927: 5–7). More directly, the 1919 first edition of *Herfsttij* had called symbolic thought, from an ethnological standpoint, `een zeer primitieve geestesfunctie` and characterized *het primitieve denken* by a weak perception of identity boundaries, using that ethnological model to account for medieval symbolism.[^24] His Indian papers also used *primitief* for earlier intellectual or medical layers.[^3]"
new = "The encounter met an existing repertoire. Huizinga later remembered reaching history from Sanskrit and comparative linguistics by a ‘salto mortale’; he also admitted that his early teaching preferred a vivid story to critical groundedness (Huizinga, 1947). Long before the American encounter, the 1919 first edition of *Herfsttij* had called symbolic thought, from an ethnological standpoint, `een zeer primitieve geestesfunctie` and characterized *het primitieve denken* by a weak perception of identity boundaries, using that ethnological model to account for medieval symbolism.[^24] His Indian papers also used *primitief* for earlier intellectual or medical layers.[^3] In 1921, reviewing Wells’s attempt to extend world history from planetary and biological development into human history, Huizinga objected that geological or biological *ontwikkeling* had little to do with ‘de functie van het historisch begrijpen’; a wider chronology did not by itself yield historical understanding (Huizinga, 1921). His critique of Spengler made the same problem comparative: exact homologies across civilizations forced particulars onto the Procrustean bed of a system, while *Preussentum und Sozialismus* turned the operation political through a *historisch-ethnografische tegenstelling* between English and Prussian character (Huizinga, 1921). On 7 April 1926, only days before his transatlantic crossing—and six days before a surviving letter places him aboard the *Berengaria*[^25]—he attacked *evolutie* as a general historical principle, defined cultural history as social morphology concerned with what connects people to one another rather than with what holds them together internally, and placed ethnology among the special cultural sciences already practising such morphology (Huizinga, 1927: 5–7). In the same theses he warned that general culture-historical terms could acquire a mythological element and suffer inflation, while period names that purported to state an era’s essence could prejudge and mislead (Huizinga, 1927: 5–7)."
if text.count(old) != 1:
    raise SystemExit(f'anchor count={text.count(old)}')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
